name: 機能提案（日本語）
description: 改善点や新機能のアイデアを提案する場合はこちら
title: "[提案] "
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: 提案の概要
      description: どんな機能を追加・改善したいか？
      placeholder: 例: ログ出力のレベルを動的に変更できるようにする
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: 背景や目的
      description: どのような課題があるか？なぜ必要か？
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案（あれば）
      description: 他の手段や回避策があれば記載してください。
  - type: textarea
    id: extra
    attributes:
      label: 補足
      description: その他関連する情報などがあれば記載してください。
