name: Feature Request (English)
description: Suggest an idea for improvement or a new feature
title: "[Feature] "
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What feature would you like to see?
      placeholder: e.g. Allow dynamic control over log verbosity.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background / Motivation
      description: What problem does this solve? Why is it needed?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives (if any)
      description: Are there other workarounds?
  - type: textarea
    id: extra
    attributes:
      label: Additional Notes
      description: Anything else you'd like to add.
