name: Enhancement Request
description: Provide supporting details for a feature in development
labels: kind/feature
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please describe the feature or enhancement you are proposing.
        Be as specific as possible about the desired functionality and behavior.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
      description: |
        Please explain the motivation for this feature.
        What problem does it solve? Who will benefit from it?
        Include any relevant use cases or scenarios.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Did you consider any alternatives?
      description: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context, mockups, examples or references about the feature request here.