name: 機能改善リクエスト
description: 開発中の機能に関する詳細を提供
labels: kind/feature
body:
  - type: textarea
    id: feature
    attributes:
      label: 何を追加してほしいですか？
      description: |
        提案する機能や改善について説明してください。
        希望する機能と動作について、できるだけ具体的に記述してください。
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: なぜこれが必要ですか？
      description: |
        この機能の動機を説明してください。
        どのような問題を解決しますか？誰が恩恵を受けますか？
        関連するユースケースやシナリオがあれば含めてください。
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案は検討しましたか？
      description: |
        検討した代替ソリューションや機能があれば、明確かつ簡潔に説明してください。

  - type: textarea
    id: additional
    attributes:
      label: 追加のコンテキスト
      description: |
        機能リクエストに関するその他のコンテキスト、モックアップ、例、参考資料などをここに追加してください。